services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_myapp
      - MARIADB_DATABASE=bitnami_myapp
      - MARIADB_PASSWORD=b1tnam1_my@pp
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    networks:
      - laravel-network

  application:
    image: 'bitnami/laravel:latest'
    environment:
      - LARAVEL_DATABASE_TYPE=mysql
      - LARAVEL_DATABASE_HOST=mariadb
      - LARAVEL_DATABASE_PORT_NUMBER=3306
      - LARAVEL_DATABASE_NAME=bitnami_myapp
      - LARAVEL_DATABASE_USER=bn_myapp
      - LARAVEL_DATABASE_PASSWORD=b1tnam1_my@pp
    ports:
      - '8000:8000'
    volumes:
      - './src:/app'
    depends_on:
      - mariadb
    networks:
      - laravel-network

volumes:
  mariadb_data:
    driver: local

networks:
  laravel-network:
    driver: bridge
